---
 - name: error handling 
   hosts: webservers
   tasks: 
    - name: naz1
      command: touch /tmp/testing/error1.txt
      ignore_errors: true
    - name: naz2
      command: touch /tmp/error2.txt


